import type { ProjectIR } from '@/core/ir/types';

export function exportMarkdownSummary(ir: ProjectIR): string {
  const lines: string[] = [];

  lines.push(`# ${ir.meta.project_name}`);
  lines.push('');
  lines.push(`- **Domain**: ${ir.meta.domain_type}`);
  lines.push(`- **Units**: ${ir.units.system_name} (${ir.units.base_length}, ${ir.units.base_force}, ${ir.units.base_mass})`);
  lines.push(`- **Created**: ${ir.meta.created_at}`);
  lines.push(`- **Updated**: ${ir.meta.updated_at}`);
  lines.push('');

  // Geometry
  lines.push('## Geometry');
  lines.push(`- Bodies: ${ir.geometry.bodies.length}`);
  lines.push(`- Faces: ${ir.geometry.faces.length}`);
  lines.push(`- Named Selections: ${ir.named_selections.length}`);
  if (ir.geometry.bodies.length > 0) {
    lines.push('');
    lines.push('| Body | Category | Shape |');
    lines.push('|------|----------|-------|');
    for (const b of ir.geometry.bodies) {
      lines.push(`| ${b.name} | ${b.category} | ${(b.metadata.shapeType as string) ?? '—'} |`);
    }
  }
  lines.push('');

  // Materials
  if (ir.materials.length > 0) {
    lines.push('## Materials');
    lines.push('');
    lines.push('| Material | Class | E | nu | rho |');
    lines.push('|----------|-------|---|----|----|');
    for (const m of ir.materials) {
      const p = m.parameter_set;
      lines.push(`| ${m.name} | ${m.class} | ${p.young_modulus.value ?? '—'} | ${p.poisson_ratio.value ?? '—'} | ${p.density.value ?? '—'} |`);
    }
    lines.push('');
  }

  // BCs
  if (ir.boundary_conditions.length > 0) {
    lines.push('## Boundary Conditions');
    lines.push('');
    lines.push('| Name | Type | Domain | Target |');
    lines.push('|------|------|--------|--------|');
    for (const bc of ir.boundary_conditions) {
      const ns = ir.named_selections.find((n) => n.id === bc.target_named_selection_id);
      lines.push(`| ${bc.name} | ${bc.bc_type} | ${bc.physics_domain} | ${ns?.name ?? '—'} |`);
    }
    lines.push('');
  }

  // Loads
  if (ir.loads.length > 0) {
    lines.push('## Loads');
    lines.push('');
    lines.push('| Name | Type | Magnitude | Direction |');
    lines.push('|------|------|-----------|-----------|');
    for (const l of ir.loads) {
      lines.push(`| ${l.name} | ${l.load_type} | ${l.magnitude} | [${l.direction.join(', ')}] |`);
    }
    lines.push('');
  }

  // Solver targets
  lines.push('## Solver Targets');
  for (const t of ir.solver_targets) {
    lines.push(`- **${t.target_name}**: ${t.enabled ? 'Enabled' : 'Disabled'} (${t.export_profile})`);
  }
  lines.push('');

  // Validation
  const v = ir.validation;
  if (v.items.length > 0) {
    lines.push('## Validation');
    lines.push(`- Errors: ${v.summary.error_count}`);
    lines.push(`- Warnings: ${v.summary.warning_count}`);
    lines.push(`- Info: ${v.summary.info_count}`);
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by FEM Modeler*');

  return lines.join('\n');
}

export function downloadMarkdownSummary(ir: ProjectIR): void {
  const md = exportMarkdownSummary(ir);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${ir.meta.project_name.replace(/\s+/g, '_')}_summary.md`;
  a.click();
  URL.revokeObjectURL(url);
}
