import { openSeesMomentLines, openSeesResultPackageLines } from './results';
import type { ExportProvenance } from '@/core/ir/provenance';
import type {
  ProjectIR
} from '@/core/ir/types';
import { singleLineComment } from './helpers';
import type { OpenSeesPyModel } from './model';

export function renderOpenSeesPyScript(ir: ProjectIR, model: OpenSeesPyModel, provenance: ExportProvenance): string {
  const lines: string[] = [
    '# OpenSeesPy script generated by FEM Modeler',
    `# Project: ${singleLineComment(ir.meta.project_name)}`,
    `# Generated: ${new Date().toISOString()}`,
    `# Units: ${singleLineComment(ir.units.system_name)}`,
    '',
    'import openseespy.opensees as ops',
    'import csv',
    'import json',
    'import platform',
    `result_provenance = json.loads(${JSON.stringify(JSON.stringify(provenance))})`,
    '',
    'ops.wipe()',
    `ops.model("basic", "-ndm", ${model.ndm}, "-ndf", ${model.ndf})`,
    '',
    '# --- Nodes ---',
  ];

  for (const node of model.nodes) lines.push(`ops.node(${node.id}, ${node.x}, ${node.y})`);

  lines.push('', '# --- Boundary Conditions ---');
  for (const fix of model.fixes) lines.push(`ops.fix(${fix.nodeId}, ${fix.dofs.join(', ')})`);

  lines.push('', '# --- Materials ---');
  for (const { tag, youngModulus } of model.materials) {
    lines.push(`ops.uniaxialMaterial("Elastic", ${tag}, ${youngModulus})`);
  }

  if (model.elementType === 'elasticBeamColumn') {
    lines.push('', '# --- Geometric Transformation ---', 'ops.geomTransf("Linear", 1)');
  }
  lines.push('', '# --- Elements ---');
  for (const element of model.elements) {
    if (model.elementType === 'elasticBeamColumn') {
      lines.push(
        `ops.element("elasticBeamColumn", ${element.id}, ${element.nodeI}, ${element.nodeJ}, ${element.area}, ${element.youngModulus}, ${element.inertiaZ as number}, ${element.transfTag})`,
      );
    } else {
      lines.push(
        `ops.element("Truss", ${element.id}, ${element.nodeI}, ${element.nodeJ}, ${element.area}, ${element.materialTag})`,
      );
    }
  }

  if (model.nodalLoads.length > 0 || model.prescribedDisplacements.length > 0) {
    lines.push('', '# --- Loads and prescribed displacements ---');
    lines.push('ops.timeSeries("Linear", 1)');
    lines.push('ops.pattern("Plain", 1, 1)');
    for (const displacement of model.prescribedDisplacements) {
      lines.push(`ops.sp(${displacement.nodeId}, ${displacement.dof}, ${displacement.value})`);
    }
    for (const load of model.nodalLoads) {
      if (model.ndf === 3) lines.push(`ops.load(${load.nodeId}, ${load.fx}, ${load.fy}, 0.0)`);
      else lines.push(`ops.load(${load.nodeId}, ${load.fx}, ${load.fy})`);
    }
  }

  lines.push('', '# --- Analysis ---');
  lines.push('ops.system("BandSPD")');
  lines.push('ops.numberer("RCM")');
  lines.push('ops.constraints("Transformation")');
  lines.push('ops.integrator("LoadControl", 1.0)');
  lines.push('ops.algorithm("Linear")');
  lines.push('ops.analysis("Static")');
  lines.push('analysis_result = ops.analyze(1)');
  lines.push('if analysis_result != 0:');
  lines.push('    with open("result_manifest.json", "w", encoding="utf-8") as failure_file:');
  lines.push('        json.dump({**result_provenance, "analysis_return_code": analysis_result}, failure_file, indent=2)');
  lines.push('    raise RuntimeError(f"OpenSees analysis failed with code {analysis_result}")');
  lines.push('', '# --- Results ---');
  lines.push('ops.reactions()');
  const resultColumns = model.ndf === 3
    ? ['node_id', 'ux_m', 'uy_m', 'rz_rad', 'reaction_x_N', 'reaction_y_N', 'reaction_mz_Nm']
    : ['node_id', 'ux_m', 'uy_m', 'reaction_x_N', 'reaction_y_N'];
  lines.push('with open("results.csv", "w", newline="", encoding="utf-8") as result_file:');
  lines.push('    result_file.write("# FEM_MODELER_PROVENANCE " + json.dumps(result_provenance, separators=(",", ":")) + "\\n")');
  lines.push(`    writer = csv.writer(result_file)`);
  lines.push(`    writer.writerow(${JSON.stringify(resultColumns)})`);
  for (const node of model.nodes) {
    lines.push(`    writer.writerow([${node.id}, *ops.nodeDisp(${node.id}), *ops.nodeReaction(${node.id})])`);
  }
  const appliedX = model.nodalLoads.reduce((sum, load) => sum + load.fx, 0);
  const appliedY = model.nodalLoads.reduce((sum, load) => sum + load.fy, 0);
  lines.push(`applied = [${appliedX}, ${appliedY}]`);
  lines.push(`reaction = [sum(ops.nodeReaction(node)[axis] for node in ${JSON.stringify(model.nodes.map((node) => node.id))}) for axis in range(2)]`);
  lines.push('imbalance = [applied[axis] + reaction[axis] for axis in range(2)]');
  lines.push('balance_tolerance = 1e-6 * max(1.0, *(abs(value) for value in applied))');
  lines.push(`balance_status = "informational_prescribed_displacement" if ${model.prescribedDisplacements.length > 0 ? 'True' : 'False'} else ("pass" if max(abs(value) for value in imbalance) <= balance_tolerance else "fail")`);
  lines.push(...openSeesMomentLines(model));
  lines.push(`result_manifest = {**result_provenance, "solver_version": ops.version(), "python_version": platform.python_version(), "analysis_return_code": analysis_result, "applied_force_N": applied, "reaction_force_N": reaction, "force_imbalance_N": imbalance, "balance_tolerance_N": balance_tolerance, "balance_status": balance_status, "applied_moment_Nm": applied_moment, "reaction_moment_Nm": reaction_moment, "moment_imbalance_Nm": moment_imbalance, "moment_balance_tolerance_Nm": moment_tolerance}`);
  lines.push('with open("result_manifest.json", "w", encoding="utf-8") as manifest_file:');
  lines.push('    json.dump(result_manifest, manifest_file, indent=2, allow_nan=False)');
  lines.push(...openSeesResultPackageLines(model, provenance));
  lines.push('if balance_status == "fail":');
  lines.push('    raise RuntimeError(f"Reaction balance check failed: imbalance={imbalance}, tolerance={balance_tolerance}")');
  lines.push('print(f"Analysis complete. Reaction balance: {balance_status}; imbalance={imbalance}")');
  return lines.join('\n');
}
