import type { ProjectIR, BoundaryCondition } from '@/core/ir/types';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { isIdentityTransform, toRadiansTuple } from '@/geometry/transforms';

export interface DOLFINxExportResult {
  success: boolean;
  script: string;
  geoFile: string;
  manifest: string;
  errors: string[];
  warnings: string[];
}

export function exportDOLFINx(ir: ProjectIR): DOLFINxExportResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  const solidBodies = ir.geometry.bodies.filter((b) => b.category === 'solid' || b.category === 'shell');
  if (solidBodies.length === 0) {
    return { success: false, script: '', geoFile: '', manifest: '', errors: ['No solid geometry found.'], warnings };
  }

  const body = solidBodies[0];
  const meta = body.metadata;
  const shapeType = meta.shapeType as string;

  // Material
  const mat = ir.materials[0];
  if (!mat) {
    errors.push('No material defined. Define a material before exporting.');
  }
  const E = mat?.parameter_set.young_modulus.value ?? 2.1e11;
  const nu = mat?.parameter_set.poisson_ratio.value ?? 0.3;
  const k = mat?.parameter_set.thermal_conductivity.value ?? 50;

  // Determine analysis type
  const isHeat = ir.meta.domain_type === 'thermal' || ir.boundary_conditions.some((bc) => bc.physics_domain === 'thermal');

  // Build Gmsh geo file
  const geoLines: string[] = [
    `// Gmsh .geo file generated by FEM Modeler`,
    `// Project: ${ir.meta.project_name}`,
    '',
    'SetFactory("OpenCASCADE");',
    '',
  ];

  // Shape definition — determine the main volume tag
  let mainVolumeTag = 1;
  if (shapeType === 'box' || shapeType === 'channel') {
    const w = meta.width as number ?? 2;
    const h = meta.height as number ?? 2;
    const d = meta.depth as number ?? 2;
    geoLines.push(`Box(1) = {${-w / 2}, ${-h / 2}, ${-d / 2}, ${w}, ${h}, ${d}};`);
  } else if (shapeType === 'plate') {
    const w = meta.width as number ?? 4;
    const t = meta.thickness as number ?? 0.2;
    const d = meta.depth as number ?? 2;
    geoLines.push(`Box(1) = {${-w / 2}, ${-t / 2}, ${-d / 2}, ${w}, ${t}, ${d}};`);
  } else if (shapeType === 'plateWithHole') {
    const w = meta.width as number ?? 4;
    const t = meta.thickness as number ?? 0.2;
    const d = meta.depth as number ?? 2;
    const r = meta.holeRadius as number ?? 0.5;
    geoLines.push(`Box(1) = {${-w / 2}, ${-t / 2}, ${-d / 2}, ${w}, ${t}, ${d}};`);
    geoLines.push(`Cylinder(2) = {0, ${-t / 2 - 0.01}, 0, 0, ${t + 0.02}, 0, ${r}};`);
    geoLines.push('BooleanDifference(3) = { Volume{1}; Delete; }{ Volume{2}; Delete; };');
    mainVolumeTag = 3;
  } else if (shapeType === 'cylinder') {
    const r = meta.radius as number ?? 1;
    const h = meta.height as number ?? 3;
    geoLines.push(`Cylinder(1) = {0, ${-h / 2}, 0, 0, ${h}, 0, ${r}};`);
  } else {
    const w = (meta.width as number) ?? 2;
    const h = (meta.height as number) ?? 2;
    const d = (meta.depth as number) ?? 2;
    geoLines.push(`Box(1) = {${-w / 2}, ${-h / 2}, ${-d / 2}, ${w}, ${h}, ${d}};`);
  }

  if (!isIdentityTransform(body.transform)) {
    appendGmshTransform(geoLines, mainVolumeTag, body.transform);
  }

  // Mesh size
  const meshSize = ir.mesh_controls.global.global_size ?? 0.5;
  geoLines.push('', `Mesh.CharacteristicLengthMax = ${meshSize};`);
  geoLines.push('Mesh.Algorithm3D = 1;');

  // Physical Volume for the main body
  geoLines.push('', `// Physical Volume for FEA domain`);
  geoLines.push(`Physical Volume("domain") = {${mainVolumeTag}};`);

  // Physical Surfaces from geometry faces referencing named selections
  geoLines.push('', '// Physical Surfaces for boundary conditions');
  const tagMap: Record<string, number> = {};
  const bodyFaces = ir.geometry.faces.filter((f) => f.body_id === body.id);

  if (bodyFaces.length > 0) {
    // Map named selections that reference faces to physical surfaces
    let pgId = 1;
    for (const ns of ir.named_selections) {
      const faceRefs = bodyFaces.filter((f) => ns.member_refs.includes(f.id));
      if (faceRefs.length > 0) {
        const faceIndices = faceRefs.map((_, i) => i + 1); // Gmsh surface IDs
        geoLines.push(`Physical Surface("${ns.name}") = {${faceIndices.join(', ')}};`);
        tagMap[ns.name] = pgId++;
      }
    }
    // Also create physical surfaces for unmapped faces (using face names)
    for (let i = 0; i < bodyFaces.length; i++) {
      const face = bodyFaces[i];
      if (!Object.keys(tagMap).includes(face.name)) {
        geoLines.push(`Physical Surface("${face.name}") = {${i + 1}};`);
        tagMap[face.name] = pgId++;
      }
    }
  } else {
    // No explicit faces — create numbered surface groups
    let pgId = 1;
    for (const ns of ir.named_selections) {
      geoLines.push(`Physical Surface("${ns.name}") = {${pgId}};`);
      tagMap[ns.name] = pgId++;
    }
    if (Object.keys(tagMap).length === 0) {
      warnings.push('No named selections for boundary tagging. BCs may not apply correctly.');
    }
  }

  const geoFile = geoLines.join('\n');

  // --- Collect BC info for Python code generation ---
  const structuralBCs = ir.boundary_conditions.filter((bc) => bc.physics_domain === 'structural');
  const thermalBCs = ir.boundary_conditions.filter((bc) => bc.physics_domain === 'thermal');

  // Python template
  const pyLines: string[] = [
    '"""DOLFINx script generated by FEM Modeler"""',
    `# Project: ${ir.meta.project_name}`,
    `# Generated: ${new Date().toISOString()}`,
    '',
    'import numpy as np',
    'from mpi4py import MPI',
    'from dolfinx import mesh, fem, io, default_scalar_type',
    'from dolfinx.fem.petsc import LinearProblem',
    'import ufl',
    '',
    '# --- Load mesh ---',
    '# Run: gmsh -3 model.geo -o model.msh',
    'domain, cell_tags, facet_tags = io.gmshio.read_from_msh("model.msh", MPI.COMM_WORLD, gdim=3)',
    '',
    `# Tag mapping: ${JSON.stringify(tagMap)}`,
    '',
  ];

  if (isHeat) {
    pyLines.push(
      '# --- Steady-state heat conduction ---',
      'V = fem.functionspace(domain, ("Lagrange", 1))',
      '',
      `k = fem.Constant(domain, default_scalar_type(${k}))  # Thermal conductivity`,
      '',
      'u = ufl.TrialFunction(V)',
      'v = ufl.TestFunction(V)',
      'a = k * ufl.inner(ufl.grad(u), ufl.grad(v)) * ufl.dx',
      'L = fem.Constant(domain, default_scalar_type(0.0)) * v * ufl.dx',
      '',
    );
    // Generate thermal BCs
    pyLines.push(...generateDOLFINxBCs(thermalBCs, ir, tagMap, 'thermal'));
    pyLines.push(
      '',
      'problem = LinearProblem(a, L, bcs=bcs)',
      'uh = problem.solve()',
      '',
      'with io.XDMFFile(MPI.COMM_WORLD, "result.xdmf", "w") as f:',
      '    f.write_mesh(domain)',
      '    f.write_function(uh)',
      'print("Heat analysis complete.")',
    );
  } else {
    pyLines.push(
      '# --- Linear elasticity ---',
      'V = fem.functionspace(domain, ("Lagrange", 1, (domain.geometry.dim,)))',
      '',
      `E = ${E}`,
      `nu = ${nu}`,
      'mu = E / (2 * (1 + nu))',
      'lmbda = E * nu / ((1 + nu) * (1 - 2 * nu))',
      '',
      'def epsilon(u):',
      '    return ufl.sym(ufl.grad(u))',
      '',
      'def sigma(u):',
      '    return lmbda * ufl.nabla_div(u) * ufl.Identity(len(u)) + 2 * mu * epsilon(u)',
      '',
      'u = ufl.TrialFunction(V)',
      'v = ufl.TestFunction(V)',
      'a = ufl.inner(sigma(u), epsilon(v)) * ufl.dx',
      'L = ufl.inner(fem.Constant(domain, (0.0,) * domain.geometry.dim), v) * ufl.dx',
      '',
    );
    // Generate structural BCs
    pyLines.push(...generateDOLFINxBCs(structuralBCs, ir, tagMap, 'structural'));
    pyLines.push(
      '',
      'problem = LinearProblem(a, L, bcs=bcs)',
      'uh = problem.solve()',
      '',
      'with io.XDMFFile(MPI.COMM_WORLD, "result.xdmf", "w") as f:',
      '    f.write_mesh(domain)',
      '    f.write_function(uh)',
      'print("Elasticity analysis complete.")',
    );
  }

  const script = pyLines.join('\n');

  const manifest = JSON.stringify({
    export_target: 'DOLFINx',
    export_time: new Date().toISOString(),
    source_project: ir.meta.project_name,
    schema_version: ir.meta.schema_version,
    analysis_type: isHeat ? 'steady_heat' : 'linear_elasticity',
    tag_map: tagMap,
    warnings, errors,
  }, null, 2);

  return { success: errors.length === 0, script, geoFile, manifest, errors, warnings };
}

function appendGmshTransform(
  lines: string[],
  volumeTag: number,
  transform: ProjectIR['geometry']['bodies'][number]['transform'],
) {
  const [sx, sy, sz] = transform.scale;
  const [rx, ry, rz] = toRadiansTuple(transform.rotation);
  const [tx, ty, tz] = transform.position;

  lines.push('', '// Apply body transform');

  if (Math.abs(sx - 1) > 1e-9 || Math.abs(sy - 1) > 1e-9 || Math.abs(sz - 1) > 1e-9) {
    lines.push(`Dilate {{0, 0, 0}, {${sx}, ${sy}, ${sz}}} { Volume{${volumeTag}}; }`);
  }
  // Apply in reverse order (Z, Y, X) so that sequential extrinsic Gmsh
  // rotations match the THREE.js Euler 'XYZ' intrinsic convention.
  if (Math.abs(rz) > 1e-9) {
    lines.push(`Rotate {{0, 0, 1}, {0, 0, 0}, ${rz}} { Volume{${volumeTag}}; }`);
  }
  if (Math.abs(ry) > 1e-9) {
    lines.push(`Rotate {{0, 1, 0}, {0, 0, 0}, ${ry}} { Volume{${volumeTag}}; }`);
  }
  if (Math.abs(rx) > 1e-9) {
    lines.push(`Rotate {{1, 0, 0}, {0, 0, 0}, ${rx}} { Volume{${volumeTag}}; }`);
  }
  if (Math.abs(tx) > 1e-9 || Math.abs(ty) > 1e-9 || Math.abs(tz) > 1e-9) {
    lines.push(`Translate {${tx}, ${ty}, ${tz}} { Volume{${volumeTag}}; }`);
  }
}

/**
 * Generate DOLFINx Dirichlet BC application code from IR boundary conditions.
 */
function generateDOLFINxBCs(
  bcs: BoundaryCondition[],
  ir: ProjectIR,
  tagMap: Record<string, number>,
  domain: 'structural' | 'thermal',
): string[] {
  const lines: string[] = [];
  lines.push('# --- Boundary conditions ---');
  lines.push('bcs = []');
  lines.push('fdim = domain.topology.dim - 1');
  lines.push('');

  if (bcs.length === 0) {
    lines.push('# No boundary conditions defined for this domain.');
    lines.push('# Add boundary conditions in the FEM Modeler UI and re-export.');
    return lines;
  }

  for (let i = 0; i < bcs.length; i++) {
    const bc = bcs[i];
    const ns = ir.named_selections.find((n) => n.id === bc.target_named_selection_id);
    const nsName = ns?.name ?? `bc_${i}`;
    const tag = tagMap[nsName];

    lines.push(`# BC ${i + 1}: "${bc.name}" (type: ${bc.bc_type}) on "${nsName}"`);

    if (tag !== undefined) {
      lines.push(`facets_${i} = facet_tags.find(${tag})`);
      lines.push(`dofs_${i} = fem.locate_dofs_topological(V, fdim, facets_${i})`);
    } else {
      // No matching tag — generate a geometric locator as fallback
      lines.push(`# Warning: No facet tag found for "${nsName}". Using geometric locator.`);
      lines.push(`# Modify the locator function to match your boundary region.`);
      lines.push(`def _bc_locator_${i}(x):`);
      if (bc.bc_type === 'fixed') {
        lines.push(`    return np.isclose(x[0], ${getFixedCoordGuess(bc)})`);
      } else {
        lines.push(`    return np.full(x.shape[1], True, dtype=bool)  # Adjust this condition`);
      }
      lines.push(`facets_${i} = mesh.locate_entities_boundary(domain, fdim, _bc_locator_${i})`);
      lines.push(`dofs_${i} = fem.locate_dofs_topological(V, fdim, facets_${i})`);
    }

    if (domain === 'structural') {
      if (bc.bc_type === 'fixed') {
        lines.push(`bc_${i} = fem.dirichletbc(np.array([0.0] * domain.geometry.dim, dtype=default_scalar_type), dofs_${i}, V)`);
      } else if (bc.bc_type === 'prescribed_displacement' && bc.values.vector) {
        const v = bc.values.vector;
        lines.push(`bc_${i} = fem.dirichletbc(np.array([${v[0]}, ${v[1]}, ${v[2]}], dtype=default_scalar_type), dofs_${i}, V)`);
      } else {
        lines.push(`bc_${i} = fem.dirichletbc(np.array([0.0] * domain.geometry.dim, dtype=default_scalar_type), dofs_${i}, V)`);
      }
    } else {
      // Thermal
      if (bc.bc_type === 'temperature' && bc.values.scalar != null) {
        lines.push(`bc_${i} = fem.dirichletbc(default_scalar_type(${bc.values.scalar}), dofs_${i}, V)`);
      } else if (bc.bc_type === 'insulation') {
        lines.push(`# Insulation (zero flux) is a natural BC — no Dirichlet BC needed.`);
        lines.push(`bc_${i} = None`);
      } else {
        lines.push(`bc_${i} = fem.dirichletbc(default_scalar_type(0.0), dofs_${i}, V)`);
      }
    }
    lines.push(`if bc_${i} is not None:`);
    lines.push(`    bcs.append(bc_${i})`);
    lines.push('');
  }

  return lines;
}

/**
 * Guess a coordinate value for fixed BC based on common patterns.
 */
function getFixedCoordGuess(bc: BoundaryCondition): string {
  // For fixed supports, usually at x_min or y_min — default to a common value
  const name = bc.name.toLowerCase();
  if (name.includes('left') || name.includes('左')) return '-1.0  # adjust to left boundary x-coordinate';
  if (name.includes('right') || name.includes('右')) return '1.0  # adjust to right boundary x-coordinate';
  if (name.includes('bottom') || name.includes('下')) return '-1.0  # adjust to bottom boundary y-coordinate';
  return '0.0  # adjust to your boundary coordinate';
}

export async function downloadDOLFINxZip(ir: ProjectIR): Promise<DOLFINxExportResult> {
  const result = exportDOLFINx(ir);
  if (!result.success && result.errors.length > 0) return result;

  const zip = new JSZip();
  zip.file('solve.py', result.script);
  zip.file('model.geo', result.geoFile);
  zip.file('export_manifest.json', result.manifest);

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${ir.meta.project_name.replace(/\s+/g, '_')}_dolfinx.zip`);
  return result;
}
