import type { ProjectIR } from '@/core/ir/types';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export interface DOLFINxExportResult {
  success: boolean;
  script: string;
  geoFile: string;
  manifest: string;
  errors: string[];
  warnings: string[];
}

export function exportDOLFINx(ir: ProjectIR): DOLFINxExportResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  const solidBodies = ir.geometry.bodies.filter((b) => b.category === 'solid' || b.category === 'shell');
  if (solidBodies.length === 0) {
    return { success: false, script: '', geoFile: '', manifest: '', errors: ['No solid geometry found.'], warnings };
  }

  const body = solidBodies[0];
  const meta = body.metadata;
  const shapeType = meta.shapeType as string;

  // Material
  const mat = ir.materials[0];
  const E = mat?.parameter_set.young_modulus.value ?? 2.1e11;
  const nu = mat?.parameter_set.poisson_ratio.value ?? 0.3;
  const k = mat?.parameter_set.thermal_conductivity.value ?? 50;

  // Determine analysis type
  const isHeat = ir.meta.domain_type === 'thermal' || ir.boundary_conditions.some((bc) => bc.physics_domain === 'thermal');

  // Build Gmsh geo file
  const geoLines: string[] = [
    `// Gmsh .geo file generated by FEM Modeler`,
    `// Project: ${ir.meta.project_name}`,
    '',
    'SetFactory("OpenCASCADE");',
    '',
  ];

  // Shape definition
  if (shapeType === 'box' || shapeType === 'channel') {
    const w = meta.width as number ?? 2;
    const h = meta.height as number ?? 2;
    const d = meta.depth as number ?? 2;
    geoLines.push(`Box(1) = {${-w / 2}, ${-h / 2}, ${-d / 2}, ${w}, ${h}, ${d}};`);
  } else if (shapeType === 'plate') {
    const w = meta.width as number ?? 4;
    const t = meta.thickness as number ?? 0.2;
    const d = meta.depth as number ?? 2;
    geoLines.push(`Box(1) = {${-w / 2}, ${-t / 2}, ${-d / 2}, ${w}, ${t}, ${d}};`);
  } else if (shapeType === 'plateWithHole') {
    const w = meta.width as number ?? 4;
    const t = meta.thickness as number ?? 0.2;
    const d = meta.depth as number ?? 2;
    const r = meta.holeRadius as number ?? 0.5;
    geoLines.push(`Box(1) = {${-w / 2}, ${-t / 2}, ${-d / 2}, ${w}, ${t}, ${d}};`);
    geoLines.push(`Cylinder(2) = {0, ${-t / 2 - 0.01}, 0, 0, ${t + 0.02}, 0, ${r}};`);
    geoLines.push('BooleanDifference(3) = { Volume{1}; Delete; }{ Volume{2}; Delete; };');
  } else if (shapeType === 'cylinder') {
    const r = meta.radius as number ?? 1;
    const h = meta.height as number ?? 3;
    geoLines.push(`Cylinder(1) = {0, ${-h / 2}, 0, 0, ${h}, 0, ${r}};`);
  } else {
    const w = (meta.width as number) ?? 2;
    const h = (meta.height as number) ?? 2;
    const d = (meta.depth as number) ?? 2;
    geoLines.push(`Box(1) = {${-w / 2}, ${-h / 2}, ${-d / 2}, ${w}, ${h}, ${d}};`);
  }

  // Mesh size
  const meshSize = ir.mesh_controls.global.global_size ?? 0.5;
  geoLines.push('', `Mesh.CharacteristicLengthMax = ${meshSize};`);
  geoLines.push('Mesh.Algorithm3D = 1;');

  // Physical groups from named selections
  let pgId = 1;
  const tagMap: Record<string, number> = {};
  for (const ns of ir.named_selections) {
    geoLines.push(`Physical Surface("${ns.name}") = {${pgId}};  // placeholder`);
    tagMap[ns.name] = pgId++;
  }

  const geoFile = geoLines.join('\n');

  // Python template
  const pyLines: string[] = [
    '"""DOLFINx script generated by FEM Modeler"""',
    `# Project: ${ir.meta.project_name}`,
    `# Generated: ${new Date().toISOString()}`,
    '',
    'import numpy as np',
    'from mpi4py import MPI',
    'from dolfinx import mesh, fem, io',
    'from dolfinx.fem.petsc import LinearProblem',
    'import ufl',
    '',
    '# --- Load mesh ---',
    '# Run: gmsh -3 model.geo -o model.msh',
    '# Then convert to XDMF if needed',
    'domain, cell_tags, facet_tags = io.gmshio.read_from_msh("model.msh", MPI.COMM_WORLD, gdim=3)',
    '',
  ];

  if (isHeat) {
    pyLines.push(
      '# --- Steady-state heat conduction ---',
      'V = fem.functionspace(domain, ("Lagrange", 1))',
      '',
      `k = fem.Constant(domain, ${k})  # Thermal conductivity`,
      '',
      'u = ufl.TrialFunction(V)',
      'v = ufl.TestFunction(V)',
      'a = k * ufl.inner(ufl.grad(u), ufl.grad(v)) * ufl.dx',
      'L = fem.Constant(domain, 0.0) * v * ufl.dx',
      '',
      '# --- Boundary conditions ---',
      '# TODO: Apply Dirichlet BCs based on facet tags',
      '# Example:',
      '# bc = fem.dirichletbc(value, dofs, V)',
      '',
      'problem = LinearProblem(a, L, bcs=[])',
      'uh = problem.solve()',
      '',
      'with io.XDMFFile(MPI.COMM_WORLD, "result.xdmf", "w") as f:',
      '    f.write_mesh(domain)',
      '    f.write_function(uh)',
      'print("Heat analysis complete.")',
    );
  } else {
    pyLines.push(
      '# --- Linear elasticity ---',
      'V = fem.functionspace(domain, ("Lagrange", 1, (domain.geometry.dim,)))',
      '',
      `E = ${E}`,
      `nu = ${nu}`,
      'mu = E / (2 * (1 + nu))',
      'lmbda = E * nu / ((1 + nu) * (1 - 2 * nu))',
      '',
      'def epsilon(u):',
      '    return ufl.sym(ufl.grad(u))',
      '',
      'def sigma(u):',
      '    return lmbda * ufl.nabla_div(u) * ufl.Identity(len(u)) + 2 * mu * epsilon(u)',
      '',
      'u = ufl.TrialFunction(V)',
      'v = ufl.TestFunction(V)',
      'a = ufl.inner(sigma(u), epsilon(v)) * ufl.dx',
      'L = ufl.inner(fem.Constant(domain, (0.0,) * domain.geometry.dim), v) * ufl.dx',
      '',
      '# --- Boundary conditions ---',
      '# TODO: Apply Dirichlet BCs based on facet tags',
      '',
      'problem = LinearProblem(a, L, bcs=[])',
      'uh = problem.solve()',
      '',
      'with io.XDMFFile(MPI.COMM_WORLD, "result.xdmf", "w") as f:',
      '    f.write_mesh(domain)',
      '    f.write_function(uh)',
      'print("Elasticity analysis complete.")',
    );
  }

  const script = pyLines.join('\n');

  const manifest = JSON.stringify({
    export_target: 'DOLFINx',
    export_time: new Date().toISOString(),
    source_project: ir.meta.project_name,
    schema_version: ir.meta.schema_version,
    analysis_type: isHeat ? 'steady_heat' : 'linear_elasticity',
    tag_map: tagMap,
    warnings, errors,
  }, null, 2);

  return { success: errors.length === 0, script, geoFile, manifest, errors, warnings };
}

export async function downloadDOLFINxZip(ir: ProjectIR): Promise<DOLFINxExportResult> {
  const result = exportDOLFINx(ir);
  if (!result.success && result.errors.length > 0) return result;

  const zip = new JSZip();
  zip.file('solve.py', result.script);
  zip.file('model.geo', result.geoFile);
  zip.file('export_manifest.json', result.manifest);

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${ir.meta.project_name.replace(/\s+/g, '_')}_dolfinx.zip`);
  return result;
}
