import type {
  GeometryBody,
  GeometryFace,
  ProjectIR
} from '@/core/ir/types';
import { isIdentityTransform, toRadiansTuple } from '@/geometry/transforms';
import { isFiniteNumber, isPositiveFinite, number, safeComment } from './helpers';
import type { ResolvedSurfaceSelection, ShapeDefinition } from './model';

export function buildGeoFile(
  ir: ProjectIR,
  body: GeometryBody,
  shape: ShapeDefinition,
  selections: Map<string, ResolvedSurfaceSelection>,
): string {
  const lines = [
    '// Gmsh .geo file generated by FEM Modeler',
    `// Project: ${safeComment(ir.meta.project_name)}`,
    '// Requires Gmsh >= 4.15 (geometric Closest surface selection).',
    '',
    'SetFactory("OpenCASCADE");',
    'Geometry.OCCBoundsUseStl = 1;',
    '',
  ];
  let volumeExpression = '1';

  if (shape.type === 'box') {
    lines.push(`Box(1) = {${number(-shape.width / 2)}, ${number(-shape.height / 2)}, ${number(-shape.depth / 2)}, ${number(shape.width)}, ${number(shape.height)}, ${number(shape.depth)}};`);
  } else if (shape.type === 'plate') {
    lines.push(`Box(1) = {${number(-shape.width / 2)}, ${number(-shape.thickness / 2)}, ${number(-shape.depth / 2)}, ${number(shape.width)}, ${number(shape.thickness)}, ${number(shape.depth)}};`);
  } else if (shape.type === 'cylinder') {
    lines.push(`Cylinder(1) = {0, ${number(-shape.height / 2)}, 0, 0, ${number(shape.height)}, 0, ${number(shape.radius)}};`);
  } else {
    lines.push(`Box(1) = {${number(-shape.width / 2)}, ${number(-shape.thickness / 2)}, ${number(-shape.depth / 2)}, ${number(shape.width)}, ${number(shape.thickness)}, ${number(shape.depth)}};`);
    lines.push(`Cylinder(2) = {0, ${number(-shape.thickness / 2)}, 0, 0, ${number(shape.thickness)}, 0, ${number(shape.holeRadius)}};`);
    lines.push('main_volume() = BooleanDifference { Volume{1}; Delete; }{ Volume{2}; Delete; };');
    volumeExpression = 'main_volume()';
  }

  if (!isIdentityTransform(body.transform)) {
    appendGmshTransform(lines, volumeExpression, body.transform);
  }

  const meshSize = ir.mesh_controls.global.global_size ?? characteristicLength(shape) / 10;
  lines.push('', `Mesh.MeshSizeMax = ${number(meshSize)};`);
  lines.push(`Mesh.ElementOrder = ${ir.mesh_controls.global.element_order};`);
  lines.push(`Mesh.Algorithm3D = ${gmshAlgorithm3D(ir.mesh_controls.global.algorithm_preference)};`);
  if (ir.mesh_controls.global.curvature_based_refinement) {
    lines.push('Mesh.MeshSizeFromCurvature = 20;');
  }
  lines.push('', '// Stable, explicit physical tag for the volume');
  lines.push(`Physical Volume("domain", 1) = {${volumeExpression}};`);

  const canonicalSelections = [...selections.values()].filter((selection) => selection.canonical);
  if (canonicalSelections.length > 0) {
    lines.push('', '// Surface tags are resolved geometrically; no OCC/Gmsh tag ordering is assumed.');
    lines.push(`domain_boundary() = Boundary { Volume{${volumeExpression}}; };`);
    const variableByFaceId = new Map<string, string>();
    let faceIndex = 0;
    for (const selection of canonicalSelections) {
      for (const face of selection.faces) {
        if (variableByFaceId.has(face.id)) continue;
        const probe = localFaceProbe(shape, face);
        if (!probe) continue;
        const transformedProbe = transformPoint(probe, body.transform);
        const variable = `resolved_face_${faceIndex++}`;
        variableByFaceId.set(face.id, variable);
        lines.push(`${variable}() = Closest {${transformedProbe.map(number).join(', ')}} { Surface{domain_boundary()}; };`);
      }
    }
    for (const selection of canonicalSelections) {
      const variables = selection.faces
        .map((face) => variableByFaceId.get(face.id))
        .filter((variable): variable is string => variable !== undefined)
        .map((variable) => `${variable}(0)`);
      lines.push(
        `Physical Surface("selection_${selection.tag}", ${selection.tag}) = {${variables.join(', ')}}; // ${safeComment(selection.selection.name)}`,
      );
    }
  }

  return lines.join('\n');
}

export function appendGmshTransform(
  lines: string[],
  volumeExpression: string,
  transform: GeometryBody['transform'],
): void {
  const [sx, sy, sz] = transform.scale;
  const [rx, ry, rz] = toRadiansTuple(transform.rotation);
  const [tx, ty, tz] = transform.position;

  lines.push('', '// Apply body transform');
  if (Math.abs(sx - 1) > 1e-9 || Math.abs(sy - 1) > 1e-9 || Math.abs(sz - 1) > 1e-9) {
    lines.push(`Dilate {{0, 0, 0}, {${number(sx)}, ${number(sy)}, ${number(sz)}}} { Volume{${volumeExpression}}; }`);
  }
  // Reverse order (Z, Y, X) matches the viewer's intrinsic THREE.js XYZ Euler transform.
  if (Math.abs(rz) > 1e-9) {
    lines.push(`Rotate {{0, 0, 1}, {0, 0, 0}, ${number(rz)}} { Volume{${volumeExpression}}; }`);
  }
  if (Math.abs(ry) > 1e-9) {
    lines.push(`Rotate {{0, 1, 0}, {0, 0, 0}, ${number(ry)}} { Volume{${volumeExpression}}; }`);
  }
  if (Math.abs(rx) > 1e-9) {
    lines.push(`Rotate {{1, 0, 0}, {0, 0, 0}, ${number(rx)}} { Volume{${volumeExpression}}; }`);
  }
  if (Math.abs(tx) > 1e-9 || Math.abs(ty) > 1e-9 || Math.abs(tz) > 1e-9) {
    lines.push(`Translate {${number(tx)}, ${number(ty)}, ${number(tz)}} { Volume{${volumeExpression}}; }`);
  }
}

export function localFaceProbe(shape: ShapeDefinition, face: GeometryFace): [number, number, number] | undefined {
  const axisFace = axisAlignedFace(face);
  if (!axisFace) return undefined;
  if (shape.type === 'cylinder') {
    return axisFace.axis === 1 ? [0, axisFace.sign * shape.height / 2, 0] : undefined;
  }

  const dimensions: [number, number, number] = shape.type === 'box'
    ? [shape.width, shape.height, shape.depth]
    : [shape.width, shape.thickness, shape.depth];
  const probe: [number, number, number] = [0, 0, 0];
  probe[axisFace.axis] = axisFace.sign * dimensions[axisFace.axis] / 2;
  if (shape.type === 'plateWithHole' && axisFace.axis === 1) {
    // The plate centre is a void; choose a point strictly between the hole and edge.
    probe[0] = (shape.holeRadius + shape.width / 2) / 2;
  }
  return probe;
}

export function transformPoint(
  point: [number, number, number],
  transform: GeometryBody['transform'],
): [number, number, number] {
  let x = point[0] * transform.scale[0];
  let y = point[1] * transform.scale[1];
  let z = point[2] * transform.scale[2];
  const [rx, ry, rz] = toRadiansTuple(transform.rotation);

  [x, y] = [Math.cos(rz) * x - Math.sin(rz) * y, Math.sin(rz) * x + Math.cos(rz) * y];
  [x, z] = [Math.cos(ry) * x + Math.sin(ry) * z, -Math.sin(ry) * x + Math.cos(ry) * z];
  [y, z] = [Math.cos(rx) * y - Math.sin(rx) * z, Math.sin(rx) * y + Math.cos(rx) * z];

  return [
    x + transform.position[0],
    y + transform.position[1],
    z + transform.position[2],
  ];
}

export function transformedVolume(shape: ShapeDefinition, body: GeometryBody): number {
  let localVolume: number;
  if (shape.type === 'box') localVolume = shape.width * shape.height * shape.depth;
  else if (shape.type === 'plate') localVolume = shape.width * shape.thickness * shape.depth;
  else if (shape.type === 'cylinder') localVolume = Math.PI * shape.radius ** 2 * shape.height;
  else localVolume = (shape.width * shape.depth - Math.PI * shape.holeRadius ** 2) * shape.thickness;
  return localVolume * Math.abs(body.transform.scale[0] * body.transform.scale[1] * body.transform.scale[2]);
}

export function totalTransformedArea(
  shape: ShapeDefinition,
  body: GeometryBody,
  faces: GeometryFace[],
): number {
  return faces.reduce((sum, face) => sum + transformedFaceArea(shape, body, face), 0);
}

export function transformedFaceArea(shape: ShapeDefinition, body: GeometryBody, face: GeometryFace): number {
  const axisFace = axisAlignedFace(face);
  const localArea = localFaceArea(shape, axisFace?.axis);
  if (!isPositiveFinite(localArea) || !axisFace) return Number.NaN;
  const [sx, sy, sz] = body.transform.scale;
  const determinant = Math.abs(sx * sy * sz);
  const inverseScaledNormalNorm = Math.sqrt(
    (axisFace.normal[0] / sx) ** 2
    + (axisFace.normal[1] / sy) ** 2
    + (axisFace.normal[2] / sz) ** 2,
  );
  return localArea * determinant * inverseScaledNormalNorm;
}

export function localFaceArea(shape: ShapeDefinition, axis: 0 | 1 | 2 | undefined): number {
  if (axis === undefined) return Number.NaN;
  if (shape.type === 'box') return boxFaceArea(axis, shape.width, shape.height, shape.depth);
  if (shape.type === 'plate') return boxFaceArea(axis, shape.width, shape.thickness, shape.depth);
  if (shape.type === 'cylinder') {
    return axis === 1 ? Math.PI * shape.radius ** 2 : Number.NaN;
  }
  if (axis === 0) return shape.depth * shape.thickness;
  if (axis === 1) return shape.width * shape.depth - Math.PI * shape.holeRadius ** 2;
  return shape.width * shape.thickness;
}

export function boxFaceArea(axis: 0 | 1 | 2, width: number, height: number, depth: number): number {
  if (axis === 0) return height * depth;
  if (axis === 1) return width * depth;
  return width * height;
}

export function axisAlignedFace(face: GeometryFace): {
  axis: 0 | 1 | 2;
  sign: -1 | 1;
  normal: [number, number, number];
} | undefined {
  if (!face.normal || !face.normal.every(isFiniteNumber)) return undefined;
  const norm = vectorNorm(face.normal);
  if (norm <= 0) return undefined;
  const normal: [number, number, number] = [
    face.normal[0] / norm,
    face.normal[1] / norm,
    face.normal[2] / norm,
  ];
  const axis = normal.findIndex((component) => Math.abs(component) > 1 - 1e-9);
  if (axis < 0 || normal.some((component, index) => index !== axis && Math.abs(component) > 1e-9)) {
    return undefined;
  }
  return {
    axis: axis as 0 | 1 | 2,
    sign: normal[axis] < 0 ? -1 : 1,
    normal,
  };
}

export function characteristicLength(shape: ShapeDefinition): number {
  if (shape.type === 'box') return Math.min(shape.width, shape.height, shape.depth);
  if (shape.type === 'plate') return Math.min(shape.width, shape.thickness, shape.depth);
  if (shape.type === 'cylinder') return Math.min(2 * shape.radius, shape.height);
  return Math.min(shape.width, shape.thickness, shape.depth, shape.holeRadius);
}

export function gmshAlgorithm3D(
  preference: ProjectIR['mesh_controls']['global']['algorithm_preference'],
): number {
  return preference === 'frontal' ? 4 : 1;
}

export function normalizedDirection(direction: [number, number, number]): [number, number, number] {
  const norm = vectorNorm(direction);
  return [direction[0] / norm, direction[1] / norm, direction[2] / norm];
}

export function vectorNorm(vector: [number, number, number]): number {
  return Math.hypot(vector[0], vector[1], vector[2]);
}
