import { dolfinxConservationLines, dolfinxResultPackageLines } from './results';
import { normalizedDirection, totalTransformedArea, transformedVolume } from './geometry';
import { convectionAmbientTemperature, convectionCoefficient, number, safeComment, structuralDofValues } from './helpers';
import type { ExportContext } from './model';

export function buildSolverScript(context: ExportContext, exportTime: string): string {
  const lines = [
    '"""DOLFINx 0.10 script generated by FEM Modeler."""',
    `# Project: ${safeComment(context.ir.meta.project_name)}`,
    `# Generated: ${exportTime}`,
    '',
    'import numpy as np',
    'import platform',
    'import dolfinx',
    'import gmsh',
    'import json',
    `result_provenance = json.loads(${JSON.stringify(JSON.stringify(context.provenance))})`,
    'from mpi4py import MPI',
    'from dolfinx import default_scalar_type, fem, io',
    'from dolfinx.fem.petsc import LinearProblem',
    'from dolfinx.io import gmsh as gmshio',
    'import ufl',
    '',
    '# Generate first: gmsh -3 model.geo -format msh4 -o model.msh',
    'mesh_data = gmshio.read_from_msh("model.msh", MPI.COMM_WORLD, rank=0, gdim=3)',
    'domain = mesh_data.mesh',
    'cell_tags = mesh_data.cell_tags',
    'facet_tags = mesh_data.facet_tags',
    'if facet_tags is None:',
    '    raise RuntimeError("model.msh has no facet tags; verify Physical Surface definitions")',
    ...requiredFacetTagChecks(context.tagBySelectionId),
    'dx = ufl.Measure("dx", domain=domain, subdomain_data=cell_tags)',
    'ds = ufl.Measure("ds", domain=domain, subdomain_data=facet_tags)',
    '',
  ];

  if (context.mode === 'thermal') {
    appendThermalProblem(lines, context);
  } else {
    appendStructuralProblem(lines, context);
  }

  lines.push(
    '',
    'problem = LinearProblem(',
    '    a,',
    '    L,',
    '    bcs=bcs,',
    '    petsc_options_prefix="fem_modeler_",',
    '    petsc_options={',
    '        "ksp_type": "preonly",',
    '        "pc_type": "lu",',
    '        "pc_factor_mat_solver_type": "mumps",',
    '        "ksp_error_if_not_converged": True,',
    '    },',
    ')',
    'try:',
    '    uh = problem.solve()',
    'except Exception as error:',
    '    if domain.comm.rank == 0:',
    '        with open("result_manifest.json", "w", encoding="utf-8") as failure_file:',
    '            json.dump({**result_provenance, "solver_error": str(error), "converged_reason": int(problem.solver.getConvergedReason())}, failure_file, indent=2)',
    '    raise',
    'converged_reason = int(problem.solver.getConvergedReason())',
    'iteration_count = int(problem.solver.getIterationNumber())',
    'if converged_reason <= 0:',
    '    raise RuntimeError(f"PETSc solve did not converge: reason={converged_reason}, iterations={iteration_count}")',
    'local_values = np.asarray(uh.x.array, dtype=float)',
    'local_minimum = float(np.min(local_values)) if local_values.size else float("inf")',
    'local_maximum = float(np.max(local_values)) if local_values.size else float("-inf")',
    'global_minimum = domain.comm.allreduce(local_minimum, op=MPI.MIN)',
    'global_maximum = domain.comm.allreduce(local_maximum, op=MPI.MAX)',
    '',
    'with io.XDMFFile(MPI.COMM_WORLD, "result.xdmf", "w") as result_file:',
    '    result_file.write_mesh(domain)',
    '    result_file.write_function(uh)',
    ...dolfinxConservationLines(context),
    ...dolfinxResultPackageLines(context),
    'if domain.comm.rank == 0:',
    '    with open("result_manifest.json", "w", encoding="utf-8") as manifest_file:',
    '        json.dump(result_manifest, manifest_file, indent=2, allow_nan=False)',
    `print("${context.mode === 'thermal' ? 'Steady heat' : 'Linear elasticity'} analysis complete.")`,
  );

  return lines.join('\n');
}

export function requiredFacetTagChecks(tagBySelectionId: Map<string, number>): string[] {
  const tags = [...new Set(tagBySelectionId.values())].sort((left, right) => left - right);
  if (tags.length === 0) return [];
  return [
    `required_facet_tags = [${tags.join(', ')}]`,
    'for required_tag in required_facet_tags:',
    '    local_facet_count = int(facet_tags.find(required_tag).size)',
    '    global_facet_count = domain.comm.allreduce(local_facet_count, op=MPI.SUM)',
    '    if global_facet_count == 0:',
    '        raise RuntimeError(f"Physical Surface tag {required_tag} is empty")',
  ];
}

export function appendStructuralProblem(lines: string[], context: ExportContext): void {
  const youngModulus = context.material.parameter_set.young_modulus.value as number;
  const poissonRatio = context.material.parameter_set.poisson_ratio.value as number;
  lines.push(
    '# --- Linear elasticity ---',
    `V = fem.functionspace(domain, ("Lagrange", ${context.ir.mesh_controls.global.element_order}, (domain.geometry.dim,)))`,
    `E = fem.Constant(domain, default_scalar_type(${number(youngModulus)}))`,
    `nu = fem.Constant(domain, default_scalar_type(${number(poissonRatio)}))`,
    'mu = E / (2 * (1 + nu))',
    'lmbda = E * nu / ((1 + nu) * (1 - 2 * nu))',
    '',
    'def epsilon(displacement):',
    '    return ufl.sym(ufl.grad(displacement))',
    '',
    'def sigma(displacement):',
    '    return lmbda * ufl.nabla_div(displacement) * ufl.Identity(domain.geometry.dim) + 2 * mu * epsilon(displacement)',
    '',
    'u = ufl.TrialFunction(V)',
    'v = ufl.TestFunction(V)',
    'a = ufl.inner(sigma(u), epsilon(v)) * dx',
    'zero_body_force = fem.Constant(domain, np.zeros(domain.geometry.dim, dtype=default_scalar_type))',
    'L = ufl.inner(zero_body_force, v) * dx',
    'n = ufl.FacetNormal(domain)',
  );

  for (let index = 0;index < context.loads.length;index++) {
    const load = context.loads[index];
    lines.push('', `# Load ${index + 1}: ${safeComment(load.name)} (${load.load_type})`);
    if (load.load_type === 'body_force') {
      const scale = load.application_mode === 'total'
        ? load.magnitude / transformedVolume(context.shape, context.body)
        : load.magnitude;
      const direction = normalizedDirection(load.direction);
      const components = direction.map((value) => value * scale);
      lines.push(`body_force_${index} = fem.Constant(domain, np.array([${components.map(number).join(', ')}], dtype=default_scalar_type))`);
      lines.push(`L += ufl.inner(body_force_${index}, v) * dx`);
    } else if (load.load_type === 'surface_traction') {
      const selection = context.surfaceSelections.get(load.target_named_selection_id)!;
      const scale = load.application_mode === 'total'
        ? load.magnitude / totalTransformedArea(context.shape, context.body, selection.faces)
        : load.magnitude;
      const components = normalizedDirection(load.direction).map((value) => value * scale);
      lines.push(`traction_${index} = fem.Constant(domain, np.array([${components.map(number).join(', ')}], dtype=default_scalar_type))`);
      lines.push(`L += ufl.inner(traction_${index}, v) * ds(${selection.tag})`);
    } else {
      const tag = context.tagBySelectionId.get(load.target_named_selection_id)!;
      lines.push(`pressure_${index} = fem.Constant(domain, default_scalar_type(${number(load.magnitude)}))`);
      lines.push(`L += ufl.inner(-pressure_${index} * n, v) * ds(${tag})`);
    }
  }

  appendStructuralBoundaryConditions(lines, context);
}

export function appendStructuralBoundaryConditions(lines: string[], context: ExportContext): void {
  lines.push('', '# --- Essential boundary conditions ---', 'bcs = []', 'fdim = domain.topology.dim - 1');
  let generatedIndex = 0;
  for (let bcIndex = 0;bcIndex < context.boundaryConditions.length;bcIndex++) {
    const bc = context.boundaryConditions[bcIndex];
    const tag = context.tagBySelectionId.get(bc.target_named_selection_id)!;
    lines.push('', `# BC ${bcIndex + 1}: ${safeComment(bc.name)} (${bc.bc_type})`);
    lines.push(`facets_bc_${bcIndex} = facet_tags.find(${tag})`);
    for (const { component, value } of structuralDofValues(bc)) {
      lines.push(`dofs_bc_${generatedIndex} = fem.locate_dofs_topological(V.sub(${component}), fdim, facets_bc_${bcIndex})`);
      lines.push(`bc_${generatedIndex} = fem.dirichletbc(default_scalar_type(${number(value)}), dofs_bc_${generatedIndex}, V.sub(${component}))`);
      lines.push(`bcs.append(bc_${generatedIndex})`);
      generatedIndex++;
    }
  }
}

export function appendThermalProblem(lines: string[], context: ExportContext): void {
  const conductivity = context.material.parameter_set.thermal_conductivity.value as number;
  lines.push(
    '# --- Steady-state heat conduction / scalar Poisson problem ---',
    `V = fem.functionspace(domain, ("Lagrange", ${context.ir.mesh_controls.global.element_order}))`,
    `k = fem.Constant(domain, default_scalar_type(${number(conductivity)}))`,
    'u = ufl.TrialFunction(V)',
    'v = ufl.TestFunction(V)',
    'a = k * ufl.inner(ufl.grad(u), ufl.grad(v)) * dx',
    'zero_source = fem.Constant(domain, default_scalar_type(0.0))',
    'L = zero_source * v * dx',
  );

  for (let index = 0;index < context.loads.length;index++) {
    const load = context.loads[index];
    lines.push('', `# Load ${index + 1}: ${safeComment(load.name)} (${load.load_type})`);
    const selection = context.ir.named_selections.find(
      (candidate) => candidate.id === load.target_named_selection_id,
    )!;
    if (load.load_type === 'volumetric_heat' || selection.target_dimension === 3) {
      const intensity = load.application_mode === 'total'
        ? load.magnitude / transformedVolume(context.shape, context.body)
        : load.magnitude;
      lines.push(`heat_source_${index} = fem.Constant(domain, default_scalar_type(${number(intensity)}))`);
      lines.push(`L += heat_source_${index} * v * dx`);
    } else {
      const surface = context.surfaceSelections.get(load.target_named_selection_id)!;
      const intensity = load.application_mode === 'total'
        ? load.magnitude / totalTransformedArea(context.shape, context.body, surface.faces)
        : load.magnitude;
      lines.push(`surface_heat_${index} = fem.Constant(domain, default_scalar_type(${number(intensity)}))`);
      lines.push(`L += surface_heat_${index} * v * ds(${surface.tag})`);
    }
  }

  for (let index = 0;index < context.boundaryConditions.length;index++) {
    const bc = context.boundaryConditions[index];
    const tag = context.tagBySelectionId.get(bc.target_named_selection_id)!;
    if (bc.bc_type === 'heat_flux') {
      // values.scalar is positive for outward heat flux q_n = -k grad(T) . n.
      lines.push('', `outward_flux_${index} = fem.Constant(domain, default_scalar_type(${number(bc.values.scalar as number)}))`);
      lines.push(`L += -outward_flux_${index} * v * ds(${tag})`);
    } else if (bc.bc_type === 'convection') {
      const h = convectionCoefficient(bc) as number;
      const ambient = convectionAmbientTemperature(bc) as number;
      lines.push('', `h_${index} = fem.Constant(domain, default_scalar_type(${number(h)}))`);
      lines.push(`ambient_temperature_${index} = fem.Constant(domain, default_scalar_type(${number(ambient)}))`);
      lines.push(`a += h_${index} * u * v * ds(${tag})`);
      lines.push(`L += h_${index} * ambient_temperature_${index} * v * ds(${tag})`);
    } else if (bc.bc_type === 'insulation') {
      lines.push('', `# ${safeComment(bc.name)}: zero outward flux is the natural boundary condition on tag ${tag}.`);
    }
  }

  appendThermalDirichletBoundaryConditions(lines, context);
}

export function appendThermalDirichletBoundaryConditions(lines: string[], context: ExportContext): void {
  lines.push('', '# --- Essential boundary conditions ---', 'bcs = []', 'fdim = domain.topology.dim - 1');
  let generatedIndex = 0;
  for (let index = 0;index < context.boundaryConditions.length;index++) {
    const bc = context.boundaryConditions[index];
    if (bc.bc_type !== 'temperature') continue;
    const tag = context.tagBySelectionId.get(bc.target_named_selection_id)!;
    lines.push('', `# BC ${index + 1}: ${safeComment(bc.name)} (temperature)`);
    lines.push(`facets_bc_${generatedIndex} = facet_tags.find(${tag})`);
    lines.push(`dofs_bc_${generatedIndex} = fem.locate_dofs_topological(V, fdim, facets_bc_${generatedIndex})`);
    lines.push(`bc_${generatedIndex} = fem.dirichletbc(default_scalar_type(${number(bc.values.scalar as number)}), dofs_bc_${generatedIndex}, V)`);
    lines.push(`bcs.append(bc_${generatedIndex})`);
    generatedIndex++;
  }
}
